/* global window */
// LCME + ASCEND Glossary data. Lightweight markdown — *italic*, **bold**, _em_.
// The view applies a small inline-formatter; no external markdown lib.

window.LCME_GLOSSARY = {
  intro:
    "Plain-English definitions for the people, places, and acronyms that come up across the 2027–28 self-study. Alphabetical, with curricular unit rosters and a topic index at the bottom.",
  letters: ["A","B","C","D","E","F","G","H","I","L","M","N","O","P","R","S","T","U"],

  entries: [
    // ─── A ───────────────────────────────────────────────────────────
    { letter: "A", term: "AAMC", expansion: "Association of American Medical Colleges",
      body: "The national association of U.S. and Canadian medical schools and teaching hospitals. Administers the MCAT, the Graduation Questionnaire (GQ), and other national surveys whose data inform program evaluation. The dashboard references mapping Sinai's MEPOs to AAMC competencies." },
    { letter: "A", term: "ACGME", expansion: "Accreditation Council for Graduate Medical Education",
      body: "The body that accredits U.S. residency programs. The 2027–28 DCI reframes Element 7.1 (\"Foundational Medical Knowledge\") around the ACGME competency framework." },
    { letter: "A", term: "Accreditation",
      body: "The LCME's verification process: confirming that ISMMS meets all 83 elements across 12 standards. The cycle runs every 8 years." },
    { letter: "A", term: "Acting Internship", aka: "AI / Sub-Internship",
      body: "A 4-week advanced clinical rotation in Phase 3 in which the student takes on intern-level responsibility under direct supervision. Develops independent clinical reasoning, patient ownership, and readiness for residency-level practice. Five AI types are required: General Surgery, Pediatrics, Medicine, Surgical Subspecialty, Emergency Medicine." },
    { letter: "A", term: "AES", expansion: "Assessment & Evaluation Subcommittee",
      body: "One of the four standing subcommittees of the EEC. Vets rubric quality, OSCE station reliability, checklist use, and equity of grade distributions before CCS approval. Monitors assessment reliability and grading consistency across sites." },
    { letter: "A", term: "Affiliation agreement",
      body: "A signed agreement governing the relationship between the medical school and a clinical site." },
    { letter: "A", term: "AI", expansion: "Artificial Intelligence",
      body: "(1) An Area of Concentration (AOC) thread within SSD. (2) Now explicitly required in the curriculum under the new Element 7.2: Table 7.2-4 requires learning objectives on appropriate use of AI in disease diagnosis and management. *(Note: \"AI\" is also used informally as an abbreviation for **Acting Internship** — read by context.)*" },
    { letter: "A", term: "AOC", expansion: "Area of Concentration",
      body: "Essential content threaded throughout the four-year curriculum at varying intensities. Four AOCs: **PCA** (Patient-Centered Advocacy), **SSD** (Scientific & Scholarly Discovery), **LPI** (Leadership & Professional Identity Formation), **HDS** (Healthcare Delivery Science). Governed by the **Curriculum Integration Subcommittee (CIS)**. THINQ in Phase 1 consolidates AOC discussions and runs deep dives." },
    { letter: "A", term: "APEX", expansion: "Clinical Preceptorship Experience",
      body: "Direct, supervised clinical exposure embedded within Phase 1 (distinct from Phase 2 clerkships)." },
    { letter: "A", term: "ASCEND",
      body: "The current ISMMS MD curriculum, designed as a response to the Second Flexner Report. Three positioning principles: integrated & advanced; whole-patient, community-facing; anchored in science & society. Built on four pillars (curricular content, curricular framework, learner assessment, support & resources) and organized in three phases anchored by PEAKS I/II/III." },
    { letter: "A", term: "Attestation",
      body: "A formal acknowledgment that a person has done or received something — e.g., faculty attestation in Mid-Clerkship Feedback, student attestation that they watched a Clerkship Essentials video, course/clerkship director attestation that they received the MEPOs. The DCI often asks for attestation *rates* as evidence." },
    { letter: "A", term: "AY", expansion: "Academic Year",
      body: "Convention used throughout the DCI. The current self-study cycle covers AY 2026–27 (the current year), looking ahead to AY 2027–28 (the year of the site visit)." },
    { letter: "A", term: "AY 2025–26 Transitional Year",
      body: "The AY 2025–26 student cohort whose Phase 2 clerkship structure (compressed rotations) differs from prior years. The anchor cohort for non-inferiority shelf-exam analyses and the LCME-aligned clerkship evaluation reports." },

    // ─── B ───────────────────────────────────────────────────────────
    { letter: "B", term: "BaseCamp",
      body: "The one-week opening of Phase 1, before the three named blocks begin." },
    { letter: "B", term: "Blackboard",
      body: "The learning management system (LMS) at Icahn Mount Sinai." },
    { letter: "B", term: "Blocks (Phase 1)",
      body: "Three named blocks structure Phase 1 across three semesters: the Foundational Block, the First Organ System–Based Block, and the Second Organ System–Based Block." },

    // ─── C ───────────────────────────────────────────────────────────
    { letter: "C", term: "CAMP", expansion: "Coaching, Advising, Mentoring, Preparation",
      body: "Six cycles in Phase 2, one after each of the first six clerkship rotations. Integrative content, scholarly progress, structured reflection." },
    { letter: "C", term: "CAS", expansion: "Clinical Assessment Services (NBME)",
      body: "The NBME service that supplies pre-validated MCQ items to medical schools for institutional use. **CAS items cannot be individually rewritten** — recommendations to address item quality must be framed around selecting alternative questions from the bank." },
    { letter: "C", term: "CCS", expansion: "Clinical Curriculum Subcommittee",
      body: "One of the four standing subcommittees of the EEC. Oversees the clinical phase: reviews clerkship plans, audits direct-observation compliance, monitors cross-site comparability trends, approves clerkship-level action plans." },
    { letter: "C", term: "CCSG", expansion: "Clinical Correlate Small Group",
      body: "A small-group session that applies foundational content from adjacent lectures to clinical cases. Common in MCG, Cardiology, Endocrinology, GI, Neuroscience, and Behavioral Science modules." },
    { letter: "C", term: "CD", expansion: "Clerkship Director",
      body: "The faculty member who runs a specific clerkship." },
    { letter: "C", term: "CIS", expansion: "Curriculum Integration Subcommittee",
      body: "One of the four standing subcommittees of the EEC. Governs the AOCs. Sets and approves standards for longitudinal integration elements, including THINQ and Areas of Concentration. Oversees the Phase 3 capstone (PEAKS III)." },
    { letter: "C", term: "CIS", expansion: "Clerkship Information Sheet",
      body: "A document students receive before each clerkship outlining what's expected. *(Note: same acronym as Curriculum Integration Subcommittee — read by context.)*" },
    { letter: "C", term: "Chronic Care Clerkship",
      body: "The 8-week longitudinal Phase 3 experience focused on the management of chronic conditions, continuity of care, multidisciplinary coordination, and the social and behavioral dimensions of long-term care." },
    { letter: "C", term: "Clerkship",
      body: "A required Phase 2 rotation in a specialty domain (Medicine, OB/GYN, Surgery, Pediatrics, Psychiatry, Neurology, Family/Ambulatory, Emergency Medicine, Neurology + Palliative Care paired). Each has its own CLOs, RCEs, and NBME shelf exam where applicable." },
    { letter: "C", term: "CLO", expansion: "Clerkship Learning Objective",
      body: "The Phase 2 analog of an MLO — what students should achieve by the end of a given clerkship. Each clerkship has its own set of CLOs that link back to MEPOs." },
    { letter: "C", term: "Coda",
      body: "The project-management platform where all 273 accreditation tasks are tracked. \"Single source of truth\" — Coda outputs are the exclusive authorized source for information entering the DCI." },
    { letter: "C", term: "Compliance",
      body: "Meeting the requirements of an LCME element. The LCME determines whether the school is compliant, in compliance with a need for monitoring, or in noncompliance, and assigns provisional ratings before the site visit." },
    { letter: "C", term: "CQI", expansion: "Continuous Quality Improvement",
      body: "The institution's stated operational standard. The self-study is framed as a demonstration of CQI in practice." },
    { letter: "C", term: "Curriculum map",
      body: "The master institutional document recording, for every session: title, hours, instructional methods, SLOs, MLOs, MEPOs, AOC, RCEs, keywords, societal problem, and assessment methods. Foundational artifact for the LCME self-study. A required appendix to the DCI." },

    // ─── D ───────────────────────────────────────────────────────────
    { letter: "D", term: "DCI", expansion: "Data Collection Instrument",
      body: "The institution's \"Book of Truth\" — the master database of responses for every accreditation element. Combines narrative responses, data tables, and required appendices for all 83 elements. Provides the evidence base for the entire accreditation survey. Submitted by July 12, 2027." },
    { letter: "D", term: "Dedicated Block",
      body: "The ~6-week Step 1 study window that follows PEAKS I in Phase 1." },
    { letter: "D", term: "Direct observation",
      body: "Workplace-based faculty observation of a student performing clinical skills (a history, physical exam, procedure). Required and audited in the clinical phase." },
    { letter: "D", term: "DX", expansion: "Required Diagnosis Experience",
      body: "An RCE subtype: a clinical presentation or diagnosis (e.g., Abdominal Pain, Altered Mental Status, Chest Pain) the student must encounter during a specified clerkship. AY 2025–26 Phase 2 has 62 required diagnosis experiences." },

    // ─── E ───────────────────────────────────────────────────────────
    { letter: "E", term: "EBM", expansion: "Evidence-Based Medicine",
      body: "Now explicitly required under the new Element 7.2: Table 7.2-5 requires three learning objectives each for \"Principles of EBM\" and \"Application of EBM to clinical decision-making\" with courses and assessment types. Also an AOC thread within SSD." },
    { letter: "E", term: "EEC", expansion: "Executive Education Committee",
      body: "The principal faculty governance body for the curriculum. Co-chaired by a Faculty Co-Chair (voting) and the Senior Associate Dean for Curricular Affairs (non-voting). Has four standing subcommittees: PCCS, CCS, CIS, AES." },
    { letter: "E", term: "Element",
      body: "One of 83 specific accreditation requirements within the 12 LCME standards. Each element has its own DCI section with narratives, tables, and supporting documentation requirements." },
    { letter: "E", term: "EOM", expansion: "End-of-Module Exam",
      body: "The summative MCQ exam at the end of a Phase 1 module. Most modules have only an EOM; a few (Anatomy, MCG, Neuroscience) also administer a Mid-Module exam." },
    { letter: "E", term: "EPO", expansion: "Educational Program Objective",
      body: "Also written as MEPO in Sinai materials. The competencies every ASCEND graduate must demonstrate. Sinai has 23 EPOs/MEPOs distributed across the seven competency domains (Patient Care, Knowledge for Practice, Practice-Based Learning and Improvement, Professionalism, Personal and Professional Development, Interpersonal and Communication Skills and Systems-Based Practice)." },
    { letter: "E", term: "Executive Summary",
      body: "The Self-Study Executive Summary — a document outlining the entire self-study process, including membership, identified strengths, and identified weaknesses. Submitted with the DCI in July 2027." },
    { letter: "E", term: "Extramural elective",
      body: "A clinical elective taken at an institution other than ISMMS. Element 11.3 requires processes for review, approval, safety monitoring, and evaluation of these." },

    // ─── F ───────────────────────────────────────────────────────────
    { letter: "F", term: "FAL", expansion: "Faculty Accreditation Lead",
      body: "The senior faculty member responsible for the integrity and synthesis of the survey package. At ISMMS: David C. Thomas, MD, MHPE (Dean for Medical Education)." },
    { letter: "F", term: "First-Time Takers",
      body: "USMLE candidates taking a step exam for the first time. NBME subject area performance graphs comparing national and Sinai first-time takers (for Step 1 and Step 2 CK) are required as new supporting documents in the 2027–28 DCI." },
    { letter: "F", term: "FIM", expansion: "Foundations of Immunology & Microbiology",
      body: "A Phase 1 Semester 1 module in the Foundational Block (POM I → MCG → Anatomy → FIM → Pathology). Covers innate and adaptive immunity, microbiology, antimicrobial mechanisms and resistance, vaccines, hypersensitivity, immunodeficiency, and clinical infectious disease application." },
    { letter: "F", term: "Flexner Report (Second)",
      body: "The contemporary call to reform medical education that ASCEND was designed to respond to. The first Flexner Report (1910) shaped 20th-century U.S. medical education; the \"Second Flexner\" framing argues the demands of modern healthcare require another fundamental rethink." },
    { letter: "F", term: "FlexTime",
      body: "Phase 2 unscheduled time during which students are *truly off* — no curricular sessions, no clinical responsibilities. Distinct from ILT (which is unstructured *curricular* schedule time)." },
    { letter: "F", term: "Flipped Classroom",
      body: "An instructional model where students review didactic content before class and use class time for application or discussion. Recommended as a target conversion for lecture-only sessions covering clinical-application content." },
    { letter: "F", term: "Formative assessment",
      body: "Assessment intended to give feedback during learning, not for grading. Element 9.7 covers formative feedback by the mid-point of courses and clerkships ≥4 weeks long; Element 9.5 covers narrative descriptions of student performance." },
    { letter: "F", term: "Formstack",
      body: "The platform that captures Mid-Clerkship Feedback faculty attestations." },
    { letter: "F", term: "Foundational Block",
      body: "Phase 1, Semester 1: POM I → MCG → Anatomy → FIM → Pathology." },

    // ─── G ───────────────────────────────────────────────────────────
    { letter: "G", term: "GME", expansion: "Graduate Medical Education",
      body: "Residency and fellowship training. ACGME accredits GME programs; LCME accredits UME programs." },
    { letter: "G", term: "GQ", expansion: "Graduation Questionnaire (AAMC)",
      body: "The AAMC-administered annual national survey of graduating medical students. Historically used as a comparative data source for the DCI. In the 2027–28 DCI, the GQ has been *removed* as a data source for several elements and replaced with ISA data and NBME subject-area performance graphs." },
    { letter: "G", term: "Governance action plan",
      body: "A formal plan to address an identified institutional issue." },
    { letter: "G", term: "GU-SRH", aka: "also SRH", expansion: "Genitourinary / Sexual & Reproductive Health",
      body: "A Phase 1 Semester 2 module (course code **MSEC6004**) in the Second Organ System Block. Covers genitourinary anatomy and histology; reproductive physiology; GU and reproductive pathophysiology; clinical diagnosis and management (contraception, abortion, infertility, STI treatment); and psychosocial/ethical dimensions (transgender healthcare, maternal health epidemiology, sexual function)." },

    // ─── H ───────────────────────────────────────────────────────────
    { letter: "H", term: "HDS", expansion: "Healthcare Delivery Science",
      body: "One of the four AOCs. Threads: Healthcare Economics, Patient Safety, Clinical Informatics, Emergency Preparedness, Quality Improvement, Public Health, Population Health." },

    // ─── I ───────────────────────────────────────────────────────────
    { letter: "I", term: "Independent Learning Time", aka: "ILT",
      body: "Phase 1: half-days free of formal curricular activities — students engage with the curriculum at their own pace, time, and style. *Distinct from FlexTime* (Phase 2, no curricular obligation at all)." },
    { letter: "I", term: "Integration (curriculum)",
      body: "Horizontal (across concurrent content) and vertical (across phases) connection of curriculum content. Element 8.3 covers how this is evaluated; AOCs are one of ASCEND's main integration mechanisms." },
    { letter: "I", term: "Interview Block",
      body: "Two protected blocks in Phase 3, timed to residency interview season, during which students don't have clinical or didactic obligations that would conflict with interviewing." },
    { letter: "I", term: "IPE", expansion: "Interprofessional Education",
      body: "Structured learning experiences with students from other health professions, training together for collaborative practice. Falls under the **LPI** AOC. Element 7.4 (Communication and Interprofessional Collaborative Skills) absorbs the content of the now-eliminated old Element 7.9. Table 7.4-2 requires phase mapping of IPE experiences." },
    { letter: "I", term: "ISA", expansion: "Independent Student Analysis",
      body: "A student-led, student-designed survey of the medical student body, independent of administration. Launches October 2026; data is analyzed and acted on through ~July 2027." },
    { letter: "I", term: "ISMMS", expansion: "Icahn School of Medicine at Mount Sinai",
      body: "The institution being accredited; the institutional home of the ASCEND curriculum." },

    // ─── L ───────────────────────────────────────────────────────────
    { letter: "L", term: "Laboratory",
      body: "A hands-on Phase 1 instructional session — primarily anatomy dissection, histology, and pathology labs." },
    { letter: "L", term: "Large Group Discussion (>12)",
      body: "Case discussion or interactive review with more than 12 students; intermediate between a lecture and a small group." },
    { letter: "L", term: "LCME", expansion: "Liaison Committee on Medical Education",
      body: "The official accrediting body for U.S. MD programs. Composed of peer leaders in medical education and academic medicine. Operates on an 8-year accreditation cycle, evaluating 12 standards and 83 elements." },
    { letter: "L", term: "Lecture",
      body: "The dominant Phase 1 instructional method (~68% of sessions). A faculty-delivered didactic session, usually to the full class." },
    { letter: "L", term: "Legacy Curriculum",
      body: "The pre-ASCEND curriculum at Sinai (Classes of 2026 and 2027). No longer producing students at the October 2027 visit, but remains part of the institutional record." },
    { letter: "L", term: "LPI", expansion: "Leadership & Professional Identity Formation",
      body: "One of the four AOCs. Threads: Medical Education, Longitudinal Care, Aging & Complex Care, Teaching, Communication, Teamwork/IPE." },

    // ─── M ───────────────────────────────────────────────────────────
    { letter: "M", term: "Match",
      body: "The National Resident Matching Program (NRMP) process that places graduating students into residency programs. Phase 3 ends with Match → Transition to Residency → Graduation." },
    { letter: "M", term: "MCF", expansion: "Mid-Clerkship Feedback",
      body: "Required formative feedback to students at weeks 2–3 of each clerkship. Three pillars: structured meeting; Formstack documentation with faculty attestation; integrated RCE review at the same session. Covered by Element 9.7." },
    { letter: "M", term: "MCG", expansion: "Molecular, Cellular & Genomic Foundations",
      body: "A Phase 1 Semester 1 foundational module (POM I → **MCG** → Anatomy → FIM → Pathology): ~67 hours across ~67 sessions. Covers biochemistry, enzyme kinetics, cell biology and signal transduction, gene expression, metabolism, genetics, and pharmacology principles (pharmacodynamics, pharmacokinetics, pharmacogenetics). Two-exam module (Mid-Module + EOM)." },
    { letter: "M", term: "MEPO", expansion: "Medical Education Program Objective",
      body: "What every ASCEND graduate must be able to do. Sinai has 23 MEPOs (numbered 1–23, with extended numbering for institutional competencies), distributed across seven competency domains — Patient Care, Knowledge for Practice, Practice-Based Learning and Improvement, Professionalism, Personal and Professional Development, Interpersonal and Communication Skills, Systems-Based Practice. MEPO mapping appears in module reports, clerkship reports, and assessment alignment. Each MLO and CLO must roll up to one or more MEPOs. *(Sometimes used interchangeably with \"EPO\" in DCI tables.)*" },
    { letter: "M", term: "Mid-Module Exam",
      body: "A summative exam administered partway through a Phase 1 module to signal mastery lag to both students and faculty. Present in Anatomy, MCG, and Neuroscience in AY 2025–26." },
    { letter: "M", term: "MLO", expansion: "Module Learning Objective",
      body: "What a student should know or be able to do by the end of a specific Phase 1 module. Each MLO links to one or more MEPOs." },
    { letter: "M", term: "Module",
      body: "The major curricular unit in Phase 1 — a defined block of integrated content (e.g., Cardiology, Endocrinology). Each module has MLOs, sessions, instructional methods, summative assessment(s), and (in most cases) an End-of-Module exam." },
    { letter: "M", term: "Module Director",
      body: "The faculty member with primary content and assessment responsibility for a Phase 1 module." },
    { letter: "M", term: "MSK", expansion: "Musculoskeletal Pathophysiology",
      body: "A Phase 1 Semester 2 module: ~33 hours across ~31 sessions. Covers MSK anatomy and physiology; pathophysiology of MSK disorders (rheumatologic, orthopedic, dermatologic); clinical assessment; management (NSAIDs, corticosteroids, DMARDs, biologics); and quality-of-life considerations." },

    // ─── N ───────────────────────────────────────────────────────────
    { letter: "N", term: "Narrative response",
      body: "Free-text DCI responses to specific prompts about how the school meets an element. One of the two main components of the DCI (the other being data tables)." },
    { letter: "N", term: "NBME", expansion: "National Board of Medical Examiners",
      body: "The organization that produces the USMLE Step exams, clerkship shelf exams, and the Clinical Assessment Services (CAS) item bank used for institutional exams. New 2027–28 DCI supporting documents include NBME subject-area performance graphs comparing national and Sinai first-time takers for USMLE Step 1 (Element 7.1) and Step 2 CK (Element 7.2) for the past three years." },
    { letter: "N", term: "Non-Inferiority / Non-Inferiority Margin",
      body: "The statistical framework used to evaluate whether the AY 2025–26 compressed-clerkship cohort performs at least as well as the legacy cohort within a pre-specified tolerance. A margin of Δ = 3.0 EPC is used for shelf exam analyses." },
    { letter: "N", term: "NRMP", expansion: "National Resident Matching Program",
      body: "The system that matches medical school graduates to residency positions. NRMP match outcomes feed into elective review (per Element 6.5 tasks)." },
    { letter: "N", term: "Nutrition",
      body: "Now explicitly required in the curriculum under the new Element 7.3. Must appear in the curriculum map." },

    // ─── O ───────────────────────────────────────────────────────────
    { letter: "O", term: "OAE", expansion: "Office of Assessment and Evaluation",
      body: "The Sinai office that supplies data and analytics across the DCI — RCE completion, OSCE results, direct-observation data, clerkship-level analytics, site-comparability indicators." },
    { letter: "O", term: "OCA", expansion: "Office of Curricular Affairs",
      body: "The Sinai administrative unit responsible for curriculum operations: curriculum mapping, accreditation documentation, and coordination among module directors, clerkship directors, and committees." },
    { letter: "O", term: "One45",
      body: "The platform tracking RCE completion (with reporting via Blackboard)." },
    { letter: "O", term: "OSCE", expansion: "Objective Structured Clinical Examination",
      body: "A performance-based assessment using standardized-patient encounters across multiple stations. OSCE results feed assessment plans, completion audits, and CQI reviews. Proposed as a vehicle for assessing MLOs that MCQs cannot validate." },

    // ─── P ───────────────────────────────────────────────────────────
    { letter: "P", term: "Pass/Fail",
      body: "The grading system in Phase 1." },
    { letter: "P", term: "PCA", expansion: "Patient-Centered Advocacy",
      body: "One of the four AOCs. Threads: Resource-Limited Healthcare, Global Health, Healthcare Access, Community Health, Patient Communication, Environmental & Health Factors, Injury Prevention, Preventive Medicine." },
    { letter: "P", term: "PCCS", expansion: "Pre-Clerkship Curriculum Subcommittee",
      body: "One of the four standing subcommittees of the EEC. Recommends Phase 1 progression expectations; monitors compliance with approved plans." },
    { letter: "P", term: "PEAKS", expansion: "Periodic Assessment of Knowledge and Skills",
      body: "The three phase capstones in ASCEND: **PEAKS I** closes Phase 1, **PEAKS II** closes Phase 2 (administered after the final clerkship rotation), **PEAKS III** is the Phase 3 capstone (overseen by CIS)." },
    { letter: "P", term: "Phase 1 — Pre-Clerkship Phase",
      body: "The preclinical phase. BaseCamp + foundational and organ-system modules across **two semesters**, plus PEAKS I + Dedicated Block + Transition to Phase 2. POM 1/2/3 and THINQ run longitudinally alongside the discrete content modules. Pass/Fail. AY 2025–26: ~15–17 modules totaling roughly 619 sessions and ~635 instructional hours." },
    { letter: "P", term: "Phase 2 — Clinical Phase",
      body: "The clerkship phase. Eight required clerkships across seven 6-week rotation slots (Neurology + Palliative Care pair into one slot). CAMP follows each of the first six rotations. PEAKS II closes the phase." },
    { letter: "P", term: "Phase 3 — Integration & Transitions",
      body: "The advanced clinical phase. Per the AY 2025–26 roster, Phase 3 combines intern-level clinical responsibility, longitudinal chronic care, and a capstone transition-to-residency experience: **Acting Internships** (4 weeks each — five required types), **Chronic Care Clerkship** (8 weeks), and **TTR / Transition to Residency** (2-week capstone immediately before Graduation). The Phase also has electives, two protected Interview Blocks timed to residency interview season, and individualized scholarly work. Phase 3 ends with Match → TTR → Graduation." },
    { letter: "P", term: "POCUS", expansion: "Point-of-Care Ultrasound",
      body: "An AOC thread within SSD." },
    { letter: "P", term: "POM", expansion: "Practice of Medicine",
      body: "The longitudinal clinical-skills spine of Phase 1, covering clinical skills, communication, ethics, and clinical reasoning. Three longitudinal modules: **POM 1** (Semester 1 — patient assessment, history-taking, physical exam, communication, ethics, basics of clinical reasoning); **POM 2** (Semester 2 — builds on POM 1 with contextual history-taking, oral case presentations, and clinical note-taking); **POM 3** (end of Phase 1 — capstone bridging to clerkships; triadic interviewing, advance directives, advanced clinical reasoning)." },
    { letter: "P", term: "Process",
      body: "One of the four task categories — describing or clarifying how something is done at the institution (vs. providing an artifact)." },
    { letter: "P", term: "PROC", expansion: "Required Procedure",
      body: "An RCE subtype: a clinical procedure (e.g., dressing change, knot-tying, suturing) the student must perform or demonstrate during a specified clerkship. AY 2025–26 Phase 2 has 15 required procedures." },
    { letter: "P", term: "Project Manager (PM)",
      body: "A subcommittee role responsible for maintaining strict project deadlines, organizing and archiving evidence, and tracking completion of action items." },
    { letter: "P", term: "Provisional rating",
      body: "The compliance rating each LCME surveyor assigns before the visit, based on the DCI. The visit then confirms strong ratings and pressure-tests weak ones." },
    { letter: "P", term: "PTP", expansion: "Patient Presentation",
      body: "A faculty-organized Phase 1 session in which a real patient shares their lived illness experience with students. **PTP is a lived-experience encounter — not a clinical-skills practice session.**" },

    // ─── R ───────────────────────────────────────────────────────────
    { letter: "R", term: "RCE", expansion: "Required Clinical Experience",
      body: "A clinical diagnosis (**DX**) or procedure (**PROC**) every student must encounter or perform during Phase 2 clerkships. Phase 1 sessions tagged with an RCE are intended as preparation for that downstream Phase 2 encounter. Aligned to LCME Element 6.2. Tracked in One45 and reported via Blackboard. The 5% alternatives threshold (how often a student met an RCE via a simulation/alternative rather than a real encounter) is a recurring DCI data point." },
    { letter: "R", term: "Resident Readiness Survey",
      body: "A new required supporting document under the 2027–28 Element 7.2 — the school's most recent Resident Readiness Survey (or equivalent), capturing how prepared graduates feel for residency." },
    { letter: "R", term: "Rotation",
      body: "A clerkship block in Phase 2. Eight clerkships fit into seven 6-week rotation slots (since Neurology + Palliative Care are paired in one slot, and Emergency Medicine + a 2-week elective share a slot)." },

    // ─── S ───────────────────────────────────────────────────────────
    { letter: "S", term: "SBP", expansion: "Systems-Based Practice",
      body: "One of the six ACGME competency domains. Element 7.7 covers SBP learning objectives + instructional formats + assessment types." },
    { letter: "S", term: "SDL", expansion: "Self-Directed Learning",
      body: "A required curricular competency. The four-step model — **Identify → Locate → Evaluate → Apply** — is mandated by Element 6.3." },
    { letter: "S", term: "Self-Study",
      body: "The institution's structured internal review for accreditation. Pulls evidence from curriculum maps, assessment analyses, program evaluation reports, and outcome data. Components include the DCI, the ISA, the Self-Study Executive Summary, and the site visit. The ISMMS Self-Study Phase runs May 2026 – June 2027." },
    { letter: "S", term: "Session",
      body: "The basic unit of instruction within a module — typically one lecture, lab, small group, PTP, or CCSG with its own SLO(s), instructional method, and ~1–2 instructional hours." },
    { letter: "S", term: "Shelf Exam",
      body: "An NBME-administered, nationally-normed multiple-choice exam taken at the end of a clerkship (Medicine, Surgery, Pediatrics, OB/GYN, Psychiatry, Neurology). Provides external benchmarking of clerkship outcomes." },
    { letter: "S", term: "Simulation",
      body: "The use of simulators, manikins, task trainers, or simulated environments as an instructional method." },
    { letter: "S", term: "Site Visit",
      body: "The 2.5-day on-campus peer review by 4–6 LCME surveyors. **October 18–20, 2027** for ISMMS. Interview-based triangulation — each issue is tested across multiple groups (students, faculty, leadership)." },
    { letter: "S", term: "Site Visit Coordinator",
      body: "The role responsible for site visit logistics. At ISMMS: Helen Ngai, MBA." },
    { letter: "S", term: "SLO", expansion: "Session Learning Objective",
      body: "What a student should take away from a single instructional session (lecture, lab, small-group, PTP, or CCSG). The primary unit used to align session content to exam items." },
    { letter: "S", term: "Small Group Discussion (<12)",
      body: "A faculty-facilitated case discussion or content review with fewer than 12 students. The standard format for CCSGs." },
    { letter: "S", term: "Societal Problem",
      body: "A curriculum-map field tagging each session to one of five approved population- or system-level problem categories. LCME-required for societal-accountability mapping." },
    { letter: "S", term: "SSD", expansion: "Scientific & Scholarly Discovery",
      body: "One of the four AOCs. Threads: AI in Medicine, POCUS, Biostatistics, Research, Literature Evaluation, EBM, Medical Decision-Making, Clinical Reasoning. The default AOC tag for biomedical-science modules." },
    { letter: "S", term: "Standard",
      body: "One of the 12 LCME standards. Each standard contains multiple elements (83 total). The 12 standards cover mission/planning/governance, leadership/administration, academic/learning environment, faculty, educational program, teacher-learner relationships, curriculum, curricular management, teaching/supervision/assessment, medical student selection, medical student academic policies, and medical student support services." },
    { letter: "S", term: "Steering Committee",
      body: "The top of the self-study org chart. Provides strategic oversight of the self-study process, synthesizes overarching themes, and gives final review and approval of the DCI. Co-chaired by the Dean (Eric Nestler) and the Dean for Medical Education (David Thomas), with a Project Manager (Chloe Martin)." },
    { letter: "S", term: "Step 1, Step 2 CK",
      body: "The first two stages of the USMLE. Step 1 is often taken in the Dedicated Block after PEAKS I (Phase 1 closeout); Step 2 CK is often taken during the clinical phases. NBME subject-area graphs for both are required as DCI supporting documentation in the 2027–28 cycle. Step 2 CK also serves as a post-hoc validation source for clerkship outcomes when the data become available." },
    { letter: "S", term: "Subcommittee (LCME task force)",
      body: "There are **eight** task force subcommittees in the full self-study: Institutional Governance; Resources, Enrollment, & Student Health; Admissions; Student Affairs; Faculty & Residents; Curriculum: Content & Instructional Methods (CCIM); Curriculum: Oversight, Management, & Evaluation (COME); Outcomes & Assessment (OA). The dashboard tracks the three curriculum subcommittees in depth." },
    { letter: "S", term: "Subcommittee (EEC)",
      body: "There are **four** standing curriculum-governance subcommittees of the EEC: PCCS (Pre-Clerkship), CCS (Clinical Curriculum), CIS (Curriculum Integration), AES (Assessment & Evaluation). *These are distinct from the eight task force subcommittees.*" },
    { letter: "S", term: "Summative assessment",
      body: "Assessment that contributes to the final grade (vs. formative assessment, which is for learning). The EOM and shelf exams are summative." },

    // ─── T ───────────────────────────────────────────────────────────
    { letter: "T", term: "Task",
      body: "A specific piece of work assigned to a subcommittee within a set timeframe. 273 active tasks were tracked at kickoff. Four categories: DCI Table, Appendix, Process, DCI Narrative Review. Status tracked in Coda; outputs from Coda are the exclusive authorized source for the DCI." },
    { letter: "T", term: "TBL", expansion: "Team-Based Learning",
      body: "A structured active-learning format with individual and team readiness-assurance tests followed by application activities." },
    { letter: "T", term: "THINQ", expansion: "The Inquiry Curriculum",
      body: "The longitudinal scholarly thread of Phase 1, organizing student inquiry across the four Areas of Concentration (PCA, SSD, LPI, HDS). Covers evidence-based medicine, clinical research methodology, and the development of a scholarly product. Runs across both Phase 1 semesters and consolidates AOC discussions." },
    { letter: "T", term: "Transition to Phase 2 / Phase 3 / Residency",
      body: "One-week (Phase 2, Phase 3) or two-week (Residency) transitional modules between major curricular stages." },
    { letter: "T", term: "TTR", expansion: "Transition to Residency",
      body: "A 2-week Phase 3 capstone preparatory experience immediately preceding graduation. Consolidates clinical skills, professional formation, and practical readiness for the first year of residency through targeted workshops, simulation, and applied clinical exercises. Occurs after Match." },

    // ─── U ───────────────────────────────────────────────────────────
    { letter: "U", term: "UME", expansion: "Undergraduate Medical Education",
      body: "The MD program (Years 1–4). LCME accredits UME; ACGME accredits GME (residency/fellowship). Despite the name, UME is at the *graduate* level — \"undergraduate\" here means before residency." },
    { letter: "U", term: "USMLE", expansion: "United States Medical Licensing Examination",
      body: "The three-step national licensing exam. Step 1 (taken at end of Phase 1), Step 2 CK (during clinical phases), Step 3 (during residency)." },
  ],

  rosters: {
    phase1: {
      title: "Phase 1 — Preclerkship modules",
      note: "POM 1, POM 2, POM 3, and THINQ run longitudinally alongside the discrete content modules.",
      columns: ["Module", "Placement", "Focus"],
      rows: [
        ["POM 1 · Practice of Medicine 1", "Sem 1 · longitudinal", "Foundational clinical skills: patient assessment, history, physical exam, communication, ethics, basics of clinical reasoning."],
        ["MCG · Molecular, Cellular & Genomic Foundations", "Sem 1", "Biochemistry, enzyme kinetics, cell biology, signal transduction, gene expression, metabolism, genetics, pharmacology principles. Mid-Module + EOM."],
        ["Anatomy", "Sem 1", "Human structure micro to macro; regional anatomy; organ systems; embryology; dissection lab. Mid-Module + EOM."],
        ["FIM · Foundations of Immunology & Microbiology", "Sem 1", "Innate & adaptive immunity, microbiology, antimicrobials and resistance, vaccines, hypersensitivity, immunodeficiency, clinical ID."],
        ["Pathology", "Sem 1 → Sem 2", "Cellular adaptation, injury, death; inflammation and repair; histopathology; organ-system pathology; neoplasia; hemodynamic disorders; lab techniques."],
        ["Hematology", "Sem 2", "Hematopoiesis; RBC and WBC disorders; hemostasis and coagulation; anemias; hematologic malignancies."],
        ["Cardiology", "Sem 1 → Sem 3", "Cardiac anatomy, electrophysiology, hemodynamics, CAD, hypertension, heart failure, arrhythmias, diagnostics, therapeutics. Largest Phase 1 module by session count."],
        ["Pulmonary Medicine · Pulmonary Pathophysiology", "Sem 2", "Pulmonary anatomy, physiology, pathophysiology; obstructive and restrictive disease, infection, vascular disease, gas exchange disorders."],
        ["Renal", "Sem 3", "Renal anatomy, glomerular filtration, tubular physiology, fluid balance, acid–base disorders, glomerular disease, renal pathophysiology."],
        ["Gastroenterology", "Sem 3", "GI anatomy and physiology, motility, hepatobiliary and pancreatic pathophysiology, GI infections, GI bleeding, liver disease."],
        ["Endocrinology", "Sem 3", "Endocrine anatomy and histology, hormonal regulation, endocrine disorders, diagnostics, pharmacology and lifestyle management."],
        ["MSK · Musculoskeletal Pathophysiology", "Sem 3", "MSK anatomy and physiology, rheumatologic/orthopedic/dermatologic disorders, clinical assessment, pharmacology (NSAIDs, corticosteroids, DMARDs, biologics)."],
        ["SRH (GU-SRH)", "Sem 3", "GU anatomy and histology, reproductive physiology, GU/reproductive pathophysiology, contraception, abortion, infertility, STIs, transgender healthcare, maternal health, sexual function."],
        ["Neuroscience", "Sem 2", "Nervous system anatomy and histology, neurophysiology, clinical localization, cognitive domains, brainstem/cranial nerve syndromes, stroke, basal ganglia, infections, tumors, neuropharmacology. Mid-Module + EOM."],
        ["Behavioral Science", "Sem 2", "Mental status assessment, psychiatric presentations, neurobiology of substance use, dementia, mood and anxiety disorders, lived-experience Patient Presentations."],
        ["POM 2 · Practice of Medicine 2", "Sem 2 · longitudinal", "Builds on POM 1: contextual history-taking, oral case presentations, clinical note-taking."],
        ["POM 3 · Practice of Medicine 3", "End of Phase 1 · longitudinal", "Capstone POM module bridging to clerkships. Triadic interviewing, advance directives, advanced clinical reasoning, pre-clerkship prep."],
        ["THINQ · The Inquiry Curriculum", "Sems 1 & 2 · longitudinal", "Scholarly thread organizing inquiry across the four AOCs; EBM, research methodology, scholarly product (MEPO 12)."],
      ],
    },
    phase2: {
      title: "Phase 2 — Required clerkships",
      note: "Each clerkship has its own CLOs, RCEs (DX + PROC), and an NBME shelf exam where applicable.",
      columns: ["Clerkship", "RCEs", "Focus", "Notes"],
      rows: [
        ["Inpatient Medicine", "19", "Comprehensive adult inpatient care; diagnostic reasoning across organ systems on the wards.", "The largest clerkship by RCE count. Abdominal pain, acid-base, anemia, chest pain, CHF, EKG/CXR interpretation, diabetes, fever, fluid/electrolyte, GI bleeding, liver disease, pneumonia, renal disease, substance use, syncope, thromboembolic disease."],
        ["Surgery–Anesthesiology", "9", "Perioperative care: surgical management plus anesthesia exposure across services.", "Abdominal pain (adult), fluid/electrolyte, postoperative pain, surgical incision; 5 procedures (airway management, dressing change, scrub technique, knot-tying, suturing)."],
        ["Pediatrics", "12", "Care of infants, children, and adolescents across acute and ambulatory settings; growth and development.", "Anemia, pediatric fever, neonatal jaundice, ear exam pathology, rash, respiratory illness, dehydration, growth/developmental milestones, HEADSSS/SSHADESS interview, immunization status, nutritional needs."],
        ["OB/GYN · Obstetrics & Gynecology", "9", "Obstetric care, gynecologic disease, and reproductive health across inpatient and outpatient settings.", "Pregnancy management; procedures (SVD assist, C-section assist, laceration repair, laparoscopic assist, hysterectomy assist, urinary catheter, obstetric ultrasound)."],
        ["Psychiatry", "7", "Diagnosis and management of psychiatric illness across acute and ambulatory settings.", "Anxiety, psychosis, personality disorder, mania, impulsivity, suicidality, depression/mood disorder."],
        ["Neurology", "9", "Diagnosis and management of nervous system disorders; localization-driven clinical reasoning.", "Altered mental state, dizziness, gait dysfunction, language dysfunction, numbness/paresthesia, seizure, stroke, weakness, systematic CT head review. Paired with Palliative Care in one rotation slot."],
        ["Emergency Medicine", "8", "Acute, undifferentiated presentations across the spectrum of severity; resuscitation and disposition.", "Abdominal pain, altered mental state, chest pain, headache, respiratory distress, shock, sepsis, trauma."],
        ["Palliative Care", "6", "Symptom management, goals-of-care, and supportive care for serious illness.", "VALUES assessment, nociceptive pain, neuropathic pain, CAM (Confusion Assessment Method), ESAS (Edmonton Symptom Assessment System) scale, goals-of-care family meeting observation. Paired with Neurology."],
      ],
    },
    phase3: {
      title: "Phase 3 — Advanced clinical experiences",
      columns: ["Unit", "Duration", "Notes"],
      rows: [
        ["Acting Internship (AI / Sub-Internship)", "4 weeks", "Intern-level responsibility under supervision. Five AI types required: General Surgery, Pediatrics, Medicine, Surgical Subspecialty (Plastic Surgery, ENT, Orthopedic Surgery, Vascular Surgery, Neurosurgery, Urology), Emergency Medicine."],
        ["Chronic Care Clerkship", "8 weeks", "Longitudinal management of chronic conditions, continuity of care, multidisciplinary coordination, social and behavioral dimensions of long-term care."],
        ["TTR — Transition to Residency", "2 weeks · capstone", "Immediately precedes graduation. Workshops, simulation, applied clinical exercises to consolidate clinical skills and residency readiness."],
      ],
    },
  },

  numbers: [
    { value: "8",   label: "Years in the LCME accreditation cycle" },
    { value: "8",   label: "Task force subcommittees" },
    { value: "12",  label: "LCME standards" },
    { value: "23",  label: "MEPOs (Sinai's program objectives)" },
    { value: "83",  label: "LCME elements (within the 12 standards)" },
    { value: "117", label: "Tasks tracked in the curriculum-subcommittee dashboard" },
    { value: "273", label: "Total active tasks at kickoff (across all 8 subcommittees)" },
  ],
  dates: [
    { when: "May 21, 2026",         what: "Self-study kickoff" },
    { when: "October 2026",         what: "ISA launch" },
    { when: "July 12, 2027",        what: "DCI + Executive Summary due" },
    { when: "October 18–20, 2027",  what: "LCME site visit" },
  ],

  topics: [
    { name: "The accreditation system",
      terms: ["LCME","AAMC","ACGME","NBME","NRMP","Accreditation","Standard","Element","DCI","ISA","Site Visit","Self-Study","Peer review","Compliance","Provisional rating","Surveyor","Triangulation","Town Hall","Tripwire","Pitfall"] },
    { name: "The team & roles",
      terms: ["Steering Committee","FAL","Site Visit Coordinator","Subcommittee (LCME task force)","Co-Chair","Project Manager","SAD","CD","Module Director"] },
    { name: "The DCI artifacts",
      terms: ["Book of Truth","Narrative response","DCI Table","Appendices","Curriculum map","Executive Summary","Attestation","Affiliation agreement","Action items","Evidence","Governance action plan","Resident Readiness Survey","GQ","NBME","OSCE","Direct observation"] },
    { name: "ASCEND identity",
      terms: ["ASCEND","ISMMS","Legacy Curriculum","AY 2025–26 Transitional Year","Flexner Report (Second)","CQI","UME","GME"] },
    { name: "ASCEND structure",
      terms: ["Phase 1","Phase 2","Phase 3","BaseCamp","Blocks (Foundational, First/Second Organ System)","POM","THINQ","PEAKS (I, II, III)","Capstone","Dedicated Block","Transition (Phase 2, Phase 3, Residency)","TTR","Chronic Care Clerkship","Acting Internship","Interview Block","ILT","FlexTime","MCF","RCE","CAMP","Rotation","Pass/Fail","Match","Preceptorship / Clinical Experience"] },
    { name: "Curricular architecture",
      terms: ["Module","Session","Clerkship","MEPO","EPO","MLO","SLO","CLO","RCE","DX","PROC","AOC","Societal Problem","Curriculum map"] },
    { name: "ASCEND governance & systems",
      terms: ["EEC","PCCS","CCS","CIS","AES","OAE","OCA","One45","Blackboard","Formstack","Coda"] },
    { name: "Areas of Concentration",
      terms: ["AOC","PCA","SSD","LPI","HDS","AI","POCUS","EBM","IPE","SDL","SBP"] },
    { name: "Instructional methods & session types",
      terms: ["Lecture","Small Group Discussion (<12)","Large Group Discussion (>12)","Laboratory","TBL","Simulation","PTP","CCSG","IPE","Preceptorship / Clinical Experience","Flipped Classroom"] },
    { name: "Assessment & psychometrics",
      terms: ["Formative assessment","Summative assessment","Competency-based","EOM","Mid-Module Exam","Shelf Exam","NBME","CAS","OSCE","Step 1","Step 2 CK","USMLE","Direct observation","MCF","Resident Readiness Survey","ISA","GQ","Non-Inferiority / Non-Inferiority Margin"] },
    { name: "Task categories (Coda)",
      terms: ["DCI Table","Appendix","Process","DCI Narrative Review"] },
  ],
};
